USE [SchedulerProduction]
GO
WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'))
BEGIN
	DECLARE @SQL NVARCHAR(2000)
	SELECT TOP 1 @SQL=('ALTER TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME
	+ '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']')
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
	WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
	EXEC (@SQL)
END


EXEC sp_MSForEachTable @command1 = "DROP TABLE ?"